<?php
    //Connect to database
    $mysqli = require __DIR__ ."/db.php";

    // Start the session if not already started
    session_start();

    //Get values from the session
    $game_session_id = $_SESSION["game_session_id"];

    //Checks if the game has started
        //See if there is a red_black_session matching the game_session_id
        $sql = sprintf("SELECT *
                            FROM red_black_session
                            WHERE game_session_id = '%s'",
                            $mysqli->real_escape_string($game_session_id) 
                        );
        $result = $mysqli->query($sql);
        if ($result->num_rows > 0) {
            //Check if the rounds_complete is NULL
            $row = $result->fetch_assoc();
            if ($row["rounds_complete"] != NULL) {
                //Set the session variable round_num = 1
                $_SESSION["round_num"] = 1;
                //Send the user over to the card selection screen
                header("Location: /CSSGametheory/HTML/studentRedBlack/studentCardSelect.php");
            }
            //Else: The page does nothing and refreshes to check if the game has been started
        }
?>
<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
	<title></title>
	<link href="/CSSGametheory/css/landingPage.css" rel="stylesheet" />
    <script src="/CSSGametheory/JavaScript/createGame.js" defer></script><!---makes sure the values are in localStorage--->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        //Refreshes the page, shows new students in the lobby
		function autoRefresh() {
			window.location = window.location.href;
		}
		setInterval('autoRefresh()', 5000);
    </script>
</head>
<body>
    
<link href="https://cssgametheory.com/CSSGametheory/css/header.css" rel="stylesheet" />
<p style="margin: 0 auto; width: 200px"><img id="logo" src="https://cssgametheory.com/CSSGametheory/Img/logo.svg"></p> 
<br>
<div class="loader"></div>
<h1 id="gameName">Red & Black Card Game</h1>
<!--- need to verify that they entered the session code generated by the teacher game select -->

<p></p>

<p></p>

<p id="connectionStatusLabel">Connection Status:<br />
<br />
<span id="connectionStatus">Success!</span></p>
<br/>
<span id="connectionStatusLabel">Waiting for Professor to Start the Game</span></p>

<p></p>

<p></p>
</body>
</html>